# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pughl\Documents\python_projects\ags-service-gui\src\mainwindow\mainwindow.ui',
# licensing of 'C:\Users\pughl\Documents\python_projects\ags-service-gui\src\mainwindow\mainwindow.ui' applies.
#
# Created: Tue Jun 19 18:25:32 2018
#      by: pyside2-uic  running on PySide2 5.11.0a1.dev1528378291
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logWindow = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.logWindow.setFont(font)
        self.logWindow.setAcceptDrops(False)
        self.logWindow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logWindow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.logWindow.setTabChangesFocus(True)
        self.logWindow.setDocumentTitle("")
        self.logWindow.setUndoRedoEnabled(False)
        self.logWindow.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.logWindow.setReadOnly(True)
        self.logWindow.setPlainText("")
        self.logWindow.setCursorWidth(0)
        self.logWindow.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.logWindow.setObjectName("logWindow")
        self.horizontalLayout.addWidget(self.logWindow)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPublishing = QtWidgets.QMenu(self.menubar)
        self.menuPublishing.setObjectName("menuPublishing")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMXD_Data_Sources_Report = QtWidgets.QAction(MainWindow)
        self.actionMXD_Data_Sources_Report.setObjectName("actionMXD_Data_Sources_Report")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionGetInstallInfo = QtWidgets.QAction(MainWindow)
        self.actionGetInstallInfo.setObjectName("actionGetInstallInfo")
        self.actionGetExecutablePath = QtWidgets.QAction(MainWindow)
        self.actionGetExecutablePath.setObjectName("actionGetExecutablePath")
        self.actionPublish_Services = QtWidgets.QAction(MainWindow)
        self.actionPublish_Services.setObjectName("actionPublish_Services")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTestLogWindow = QtWidgets.QAction(MainWindow)
        self.actionTestLogWindow.setObjectName("actionTestLogWindow")
        self.menuFile.addAction(self.actionExit)
        self.menuReports.addAction(self.actionMXD_Data_Sources_Report)
        self.menuHelp.addAction(self.actionGetInstallInfo)
        self.menuHelp.addAction(self.actionGetExecutablePath)
        self.menuHelp.addAction(self.actionTestLogWindow)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuPublishing.addAction(self.actionPublish_Services)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPublishing.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "AGS Service Publisher", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menuReports.setTitle(QtWidgets.QApplication.translate("MainWindow", "Reports", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.menuPublishing.setTitle(QtWidgets.QApplication.translate("MainWindow", "Publishing", None, -1))
        self.actionMXD_Data_Sources_Report.setText(QtWidgets.QApplication.translate("MainWindow", "MXD Data Sources Report", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "E&xit", None, -1))
        self.actionGetInstallInfo.setText(QtWidgets.QApplication.translate("MainWindow", "GetInstallInfo", None, -1))
        self.actionGetExecutablePath.setText(QtWidgets.QApplication.translate("MainWindow", "GetExecutablePath", None, -1))
        self.actionPublish_Services.setText(QtWidgets.QApplication.translate("MainWindow", "Publish Services", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About...", None, -1))
        self.actionTestLogWindow.setText(QtWidgets.QApplication.translate("MainWindow", "TestLogWindow", None, -1))

