# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pughl\Documents\python_projects\ags-service-gui\src\mxdreportdialog\mxdreportdialog.ui',
# licensing of 'C:\Users\pughl\Documents\python_projects\ags-service-gui\src\mxdreportdialog\mxdreportdialog.ui' applies.
#
# Created: Tue Jun 19 18:25:32 2018
#      by: pyside2-uic  running on PySide2 5.11.0a1.dev1528378291
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MXDReportDialog(object):
    def setupUi(self, MXDReportDialog):
        MXDReportDialog.setObjectName("MXDReportDialog")
        MXDReportDialog.resize(544, 416)
        MXDReportDialog.setWindowTitle("MXD Data Sources Report")
        MXDReportDialog.setSizeGripEnabled(True)
        MXDReportDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(MXDReportDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(MXDReportDialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.servicesTree = QtWidgets.QTreeWidget(self.layoutWidget)
        self.servicesTree.setAlternatingRowColors(True)
        self.servicesTree.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.servicesTree.setColumnCount(2)
        self.servicesTree.setObjectName("servicesTree")
        self.servicesTree.header().setMinimumSectionSize(100)
        self.servicesTree.header().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.servicesTree)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.envsTree = QtWidgets.QTreeWidget(self.layoutWidget1)
        self.envsTree.setAlternatingRowColors(True)
        self.envsTree.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.envsTree.setColumnCount(2)
        self.envsTree.setObjectName("envsTree")
        self.envsTree.header().setMinimumSectionSize(100)
        self.envsTree.header().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.envsTree)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(MXDReportDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.widget = QtWidgets.QWidget(MXDReportDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.outputfileLineEdit = QtWidgets.QLineEdit(self.widget)
        self.outputfileLineEdit.setObjectName("outputfileLineEdit")
        self.horizontalLayout_4.addWidget(self.outputfileLineEdit)
        self.outputfileButton = QtWidgets.QPushButton(self.widget)
        self.outputfileButton.setObjectName("outputfileButton")
        self.horizontalLayout_4.addWidget(self.outputfileButton)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)

        self.retranslateUi(MXDReportDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), MXDReportDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), MXDReportDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MXDReportDialog)

    def retranslateUi(self, MXDReportDialog):
        self.label.setText(QtWidgets.QApplication.translate("MXDReportDialog", "Services to report:", None, -1))
        self.servicesTree.headerItem().setText(0, QtWidgets.QApplication.translate("MXDReportDialog", "Name", None, -1))
        self.servicesTree.headerItem().setText(1, QtWidgets.QApplication.translate("MXDReportDialog", "Type", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MXDReportDialog", "Environments to report:", None, -1))
        self.envsTree.headerItem().setText(0, QtWidgets.QApplication.translate("MXDReportDialog", "Name", None, -1))
        self.envsTree.headerItem().setText(1, QtWidgets.QApplication.translate("MXDReportDialog", "Type", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MXDReportDialog", "Output file:", None, -1))
        self.outputfileButton.setText(QtWidgets.QApplication.translate("MXDReportDialog", "...", None, -1))

